# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ runCommand, fetchzip, fetchgit }:

runCommand "zig-packages" {} ''
  mkdir -p $out
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/wuffs-122037b39d577ec2db3fd7b2130e7b69ef6cc1807d68607a7c232c958315d381b5cd.tar.gz";
    hash = "sha256-XbupK4QYnPudUlO5tRWrQRncGHITzJL//Yk/E7WNxYk=";
  }} $out/N-V-__8AAAzZywE3s51XfsLbP9eyEw57ae9swYB9aGB6fCMs
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/zlib-1220fed0c74e1019b3ee29edae2051788b080cd96e90d56836eea857b0b966742efb.tar.gz";
    hash = "sha256-TkPLWSN5QcPlL9D0kc/yhH0/puE9bFND24aj5NVDKYs=";
  }} $out/N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/glslang-12201278a1a05c0ce0b6eb6026c65cd3e9247aa041b1c260324bf29cee559dd23ba1.tar.gz";
    hash = "sha256-B6jVCeoFjd2H6+7tIses+Kj8DgHS6E2dkVzQAIzDHEc=";
  }} $out/N-V-__8AABzkUgISeKGgXAzgtutgJsZc0-kkeqBBscJgMkvy
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/pixels-12207ff340169c7d40c570b4b6a97db614fe47e0d83b5801a932dcd44917424c8806.tar.gz";
    hash = "sha256-kXYGO0qn2PfyOYCrRA49BHIgTzdmKhI8SNO1ZKfUYEE=";
  }} $out/N-V-__8AADYiAAB_80AWnH1AxXC0tql9thT-R-DYO1gBqTLc
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/gettext-0.24.tar.gz";
    hash = "sha256-FBb80LX5WtgB9O32HRhg9g8aQSyOmsFW8qonySSlaO4=";
  }} $out/N-V-__8AADcZkgn4cMhTUpIz6mShCKyqqB-NBtf_S2bHaTC-
  cp -r ${fetchzip {
    url = "https://codeload.github.com/ocornut/imgui/tar.gz/refs/tags/v1.92.5-docking";
    hash = "sha256-/jVT7+874LCeSF/pdNVTFoSOfRisSqxCJnt5/SGCXPQ=";
  }} $out/N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/harfbuzz-11.0.0.tar.xz";
    hash = "sha256-g9jRP85C9XGOKrnjtOgCa+u1WqJsEYC4W3IQjdMkbJ0=";
  }} $out/N-V-__8AAG02ugUcWec-Ndp-i7JTsJ0dgF8nnJRUInkGLG7G
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/libxml2-2.11.5.tar.gz";
    hash = "sha256-2SEzGhMeIHoHe9EKV6LgPLBXdmrxWWgnLYwUMZFWxNQ=";
  }} $out/N-V-__8AAG3RoQEyRC2Vw7Qoro5SYBf62IHn3HjqtNVY6aWK
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/highway-66486a10623fa0d72fe91260f96c892e41aceb06.tar.gz";
    hash = "sha256-1xn+WAxeQyrz9KA3y4EOCr5Z94mom7J5TNdippPe2Sw=";
  }} $out/N-V-__8AAGmZhABbsPJLfbqrh6JTHsXhY6qCaLAQyx25e0XE
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/utfcpp-1220d4d18426ca72fc2b7e56ce47273149815501d0d2395c2a98c726b31ba931e641.tar.gz";
    hash = "sha256-oKVFUjCvkHjqifZe98aUe68IBUaAZYWU2S2rxyAA9Cg=";
  }} $out/N-V-__8AAHffAgDU0YQmynL8K35WzkcnMUmBVQHQ0jlcKpjH
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/oniguruma-1220c15e72eadd0d9085a8af134904d9a0f5dfcbed5f606ad60edc60ebeccd9706bb.tar.gz";
    hash = "sha256-aQdK31CIkzXZel+k8GZt5cv80sTkas9dL28RAVbFheU=";
  }} $out/N-V-__8AAHjwMQDBXnLq3Q2QhaivE0kE2aD138vtX2Bq1g7c
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/JetBrainsMono-2.304.tar.gz";
    hash = "sha256-4cVt/b0NCEsWnCsKR5lU6HC/fQfF7L2gpvaLRSMIiZM=";
  }} $out/N-V-__8AAIC5lwAVPJJzxnCAahSvZTIlG-HhtOvnM1uh-66x
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/fontconfig-2.14.2.tar.gz";
    hash = "sha256-TmDanBHYpKnBO74wZOV6fYReO/hhjzBhYfO7mHJjVlw=";
  }} $out/N-V-__8AAIrfdwARSa-zMmxWwFuwpXf1T3asIN7s5jqi9c1v
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/libpng-1220aa013f0c83da3fb64ea6d327f9173fa008d10e28bc9349eac3463457723b1c66.tar.gz";
    hash = "sha256-Mo1M8TuVaoSIb7Hy2u6zgjZ1DKgpmgNmGRP6dGg/aTs=";
  }} $out/N-V-__8AAJrvXQCqAT8Mg9o_tk6m0yf5Fz-gCNEOKLyTSerD
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/freetype-1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d.tar.gz";
    hash = "sha256-Io9k8xmOKrk+4GSi3PUU60X68T4BpG8dru1/KO+jVRk=";
  }} $out/N-V-__8AAKLKpwC4H27Ps_0iL3bPkQb-z6ZVSrB-x_3EEkub
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/plasma_wayland_protocols-12207e0851c12acdeee0991e893e0132fc87bb763969a585dc16ecca33e88334c566.tar.gz";
    hash = "sha256-iWRv3+OfmHxmeCJ8m0ChjgZX6mwXlcFmK8P/Vt8gDj4=";
  }} $out/N-V-__8AAKYZBAB-CFHBKs3u4JkeiT4BMvyHu3Y5aaWF3Bbs
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/ghostty-themes-release-20260202-151632-49169e9.tgz";
    hash = "sha256-hS1DPREe8jzLnjpitFp8uDnwfwqtxHsMUYBgNtVTL0E=";
  }} $out/N-V-__8AAKlTAwClvdUfsAoiLgM6sb2NPZNnS6wzCiIs252Z
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/wayland-9cb3d7aa9dc995ffafdbdef7ab86a949d0fb0e7d.tar.gz";
    hash = "sha256-swXtymMipE7vmifM5HmhXHhxfxBLE66NBAeTcywBiIg=";
  }} $out/N-V-__8AAKrHGAAs2shYq8UkE6bGcR1QJtLTyOE_lcosMn6t
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/wayland-protocols-258d8f88f2c8c25a830c6316f87d23ce1a0f12d9.tar.gz";
    hash = "sha256-93X0dLoCgQcJzjBCBS9YHb4fPVa3wC2lixXcxoLuBtM=";
  }} $out/N-V-__8AAKw-DAAaV8bOAAGqA0-oD7o-HNIlPFYKRXSPT03S
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/gtk4-layer-shell-1.1.0.tar.gz";
    hash = "sha256-UGhFeaBBIfC4ToWdyoX+oUzLlqJsjF++9U7mtszE0y0=";
  }} $out/N-V-__8AALiNBAA-_0gprYr92CjrMj1I5bqNu0TSJOnjFNSr
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/breakpad-b99f444ba5f6b98cac261cbb391d8766b34a5918.tar.gz";
    hash = "sha256-Pro7cOujfdYAc3REK6HDyi/tlyH+Sq5Yt/OjQ0lg4FE=";
  }} $out/N-V-__8AALw2uwF_03u4JRkZwRLc3Y9hakkYV7NKRR9-RIZJ
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/NerdFontsSymbolsOnly-3.4.0.tar.gz";
    hash = "sha256-rNmRV0t4+KP2B1VoC+GLVFrxA80YeT+4EHpl4TUvDnQ=";
  }} $out/N-V-__8AAMVLTABmYkLqhZPLXnMl-KyN38R8UVYqGrxqO26s
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/DearBindings_v0.17_ImGui_v1.92.5-docking.tar.gz";
    hash = "sha256-oaCuoX0dxlEB6IDQFqcGgalHxabBc1tfe6Q7gS0MiIo=";
  }} $out/N-V-__8AANT61wB--nJ95Gj_ctmzAtcjloZ__hRqNw5lC1Kr
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/spirv_cross-1220fb3b5586e8be67bc3feb34cbe749cf42a60d628d2953632c2f8141302748c8da.tar.gz";
    hash = "sha256-7unyC2qPiuyaotRKCVC8HRT+3Kfj9qIxEKVyBlmpMds=";
  }} $out/N-V-__8AANb6pwD7O1WG6L5nvD_rNMvnSc9Cpg1ijSlTYywv
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/sentry-1220446be831adcca918167647c06c7b825849fa3fba5f22da394667974537a9c77e.tar.gz";
    hash = "sha256-S9fkxLCeQdHOt1FUa8CcZMmORNcxwQSuchng/dNq4g8=";
  }} $out/N-V-__8AAPlZGwBEa-gxrcypGBZ2R8Bse4JYSfo_ul8i2jlG
  cp -r ${fetchgit {
    url = "https://github.com/ghostty-org/ghostty.git";
    rev = "c1207afbec2c1c829ea8d3de4ffe1c391944b244";
    hash = "sha256-xWAESmqfG5Xlrak/SL65U5VKIn9QI+mMZnyzEqNxEv0=";
  }} $out/ghostty-1.3.0-dev-5UdBC7otTQSkYgTQAiP03iZL48fg-hOXtUxqpmXIlIdc
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/gobject-2025-11-08-23-1.tar.zst";
    hash = "sha256-OxS9/XC5aMJj1KhOcFP1ZZN7PI4ADw4f7ocx6V64mOc=";
  }} $out/gobject-0.3.0-Skun7ANLnwDvEfIpVmohcppXgOvg_I6YOJFmPIsKfXk-
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/libxev-34fa50878aec6e5fa8f532867001ab3c36fae23e.tar.gz";
    hash = "sha256-1B9oJExVyOWRj+Y9d9eHkOBTlOYuEkcwGBUKdlgRhkg=";
  }} $out/libxev-0.0.0-86vtc4IcEwCqEYxEYoN_3KXmc6A9VLcm22aVImfvecYs
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/uucode-31655fba3c638229989cc524363ef5e3c7b580c1.tar.gz";
    hash = "sha256-yF/fymRuqt1QtKwBTg6yD2jhlOn9F51soRRXWvChP3Q=";
  }} $out/uucode-0.1.0-ZZjBPicPTQDlG6OClzn2bPu7ICkkkyWrTB6aRsBr-A1E
  cp -r ${fetchgit {
    url = "https://github.com/jacobsandlund/uucode";
    rev = "5f05f8f83a75caea201f12cc8ea32a2d82ea9732";
    hash = "sha256-sHPh+TQSdUGus/QTbj7KSJJkTuNTrK4VNmQDjS30Lf8=";
  }} $out/uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/vaxis-7dbb9fd3122e4ffad262dd7c151d80d863b68558.tar.gz";
    hash = "sha256-zTyrZrIffM+GJIt973tKDeWHmOCwbn7KLDdQxSiK00Y=";
  }} $out/vaxis-0.5.1-BWNV_LosCQAGmCCNOLljCIw6j6-yt53tji6n6rwJ2BhS
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/zig_wayland-1b5c038ec10da20ed3a15b0b2a6db1c21383e8ea.tar.gz";
    hash = "sha256-1wRkixysjdFMyrATxlXdukAc34MwfNj0B6ydYVn+UKw=";
  }} $out/wayland-0.5.0-dev-lQa1khrMAQDJDwYFKpdH3HizherB7sHo5dKMECfvxQHe
  cp -r ${fetchzip {
    url = "https://codeload.github.com/vancluever/z2d/tar.gz/refs/tags/v0.10.0";
    hash = "sha256-qD+XexnAjSanRAwr5ZIaPY1aQhNW5DFVJ4PYLwhIr2E=";
  }} $out/z2d-0.10.0-j5P_Hu-6FgBsZNgwphIqh17jDnj8_yPtD8yzjO6PpHRQ
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/zf-3c52637b7e937c5ae61fd679717da3e276765b23.tar.gz";
    hash = "sha256-BfAZILill3I/nBf1oWwol77N34Jcpm4hudC+XSeMgZY=";
  }} $out/zf-0.10.3-OIRy8RuJAACKA3Lohoumrt85nRbHwbpMcUaLES8vxDnh
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/zig_js-04db83c617da1956ac5adc1cb9ba1e434c1cb6fd.tar.gz";
    hash = "sha256-r6GdXwrv+jTu0AkTlyN/FuO+N4X+l20gsbS59wrE7V4=";
  }} $out/zig_js-0.0.0-rjCAV-6GAADxFug7rDmPH-uM_XcnJ5NmuAMJCAscMjhi
  cp -r ${fetchzip {
    url = "https://deps.files.ghostty.org/zig_objc-f356ed02833f0f1b8e84d50bed9e807bf7cdc0ae.tar.gz";
    hash = "sha256-jWFQ5BrV880qqa9KypltWuRLqNSh21rDxt6Jxp0EoMM=";
  }} $out/zig_objc-0.0.0-Ir_Sp5gTAQCvxxR7oVIrPXxXwsfKgVP7_wqoOQrZjFeK
  cp -r ${fetchzip {
    url = "https://codeload.github.com/ivanstepanovftw/zigimg/tar.gz/d7b7ab0ba0899643831ef042bd73289510b39906";
    hash = "sha256-vkcTloGX+vRw7e6GYJLO9eocYaEOYjXYE0dT7jscZ4A=";
  }} $out/zigimg-0.1.0-8_eo2vHnEwCIVW34Q14Ec-xUlzIoVg86-7FU2ypPtxms
''
